DROP TABLE IF EXISTS possible_answers;
DROP TABLE IF EXISTS responses;
DROP TABLE IF EXISTS questions;
DROP TABLE IF EXISTS surveys;
DROP TYPE IF EXISTS question_type;

CREATE TABLE surveys (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    descrip TEXT,
    creation_date TIMESTAMPTZ DEFAULT CURRENT_DATE,
    open_date TIMESTAMPTZ DEFAULT CURRENT_DATE,
    close_date TIMESTAMPTZ,
    image_url TEXT,
    author TEXT
);

CREATE TYPE question_type AS ENUM ('text', 'radio', 'checkbox');
CREATE TABLE questions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_id INT,
    FOREIGN KEY (survey_id) REFERENCES surveys(id) ON DELETE CASCADE,
    qtext TEXT NOT NULL,
    qdesc TEXT,
    qtype question_type,
    qweight INT DEFAULT 1,
    is_required BOOLEAN DEFAULT FALSE
);

CREATE TABLE possible_answers (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_id INT,
    question_id INT,
    FOREIGN KEY (survey_id) REFERENCES surveys(id) ON DELETE CASCADE,
    FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE,
    atext TEXT NOT NULL,
    avalue TEXT,
    index INT
);

CREATE TABLE responses (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_id INT,
    question_id INT,
    FOREIGN KEY (survey_id) REFERENCES surveys(id) ON DELETE CASCADE,
    FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE,
    response TEXT
);